# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='task.Task', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='description',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='task.Task', verbose_name='Задача'),
        ),
    ]
