# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20180811_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='task.Task', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='description',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='description', to='task.Task', verbose_name='Задача'),
        ),
    ]
